// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_key.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (key, user_id, payload_hash, response_metadata)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE SET
    payload_hash = EXCLUDED.payload_hash,
    response_metadata = EXCLUDED.response_metadata,
    updated_at = now()
RETURNING key, user_id, payload_hash, response_metadata, updated_at
`

type CreateIdempotencyKeyParams struct {
	Key              string      `json:"key"`
	UserID           pgtype.UUID `json:"user_id"`
	PayloadHash      string      `json:"payload_hash"`
	ResponseMetadata []byte      `json:"response_metadata"`
}

type CreateIdempotencyKeyRow struct {
	Key              string             `json:"key"`
	UserID           pgtype.UUID        `json:"user_id"`
	PayloadHash      string             `json:"payload_hash"`
	ResponseMetadata []byte             `json:"response_metadata"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (CreateIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.Key,
		arg.UserID,
		arg.PayloadHash,
		arg.ResponseMetadata,
	)
	var i CreateIdempotencyKeyRow
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.PayloadHash,
		&i.ResponseMetadata,
		&i.UpdatedAt,
	)
	return i, err
}
