// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyKey struct {
	Key              string             `json:"key"`
	UserID           pgtype.UUID        `json:"user_id"`
	PayloadHash      string             `json:"payload_hash"`
	ResponseMetadata []byte             `json:"response_metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type MonthlyStatement struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	PortfolioName string             `json:"portfolio_name"`
	ReferenceDate pgtype.Date        `json:"reference_date"`
	IngestKey     string             `json:"ingest_key"`
	RawPayload    []byte             `json:"raw_payload"`
	ParsedPayload []byte             `json:"parsed_payload"`
	Status        string             `json:"status"`
	Source        string             `json:"source"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Portfolio struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  pgtype.Text        `json:"display_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
