// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monthly_statement.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMonthlyStatement = `-- name: CreateMonthlyStatement :one
INSERT INTO monthly_statements (user_id, portfolio_name, reference_date, ingest_key, raw_payload, parsed_payload, status, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, ingest_key, status, submitted_at, source
`

type CreateMonthlyStatementParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	PortfolioName string      `json:"portfolio_name"`
	ReferenceDate pgtype.Date `json:"reference_date"`
	IngestKey     string      `json:"ingest_key"`
	RawPayload    []byte      `json:"raw_payload"`
	ParsedPayload []byte      `json:"parsed_payload"`
	Status        string      `json:"status"`
	Source        string      `json:"source"`
}

type CreateMonthlyStatementRow struct {
	ID          pgtype.UUID        `json:"id"`
	IngestKey   string             `json:"ingest_key"`
	Status      string             `json:"status"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	Source      string             `json:"source"`
}

func (q *Queries) CreateMonthlyStatement(ctx context.Context, arg CreateMonthlyStatementParams) (CreateMonthlyStatementRow, error) {
	row := q.db.QueryRow(ctx, createMonthlyStatement,
		arg.UserID,
		arg.PortfolioName,
		arg.ReferenceDate,
		arg.IngestKey,
		arg.RawPayload,
		arg.ParsedPayload,
		arg.Status,
		arg.Source,
	)
	var i CreateMonthlyStatementRow
	err := row.Scan(
		&i.ID,
		&i.IngestKey,
		&i.Status,
		&i.SubmittedAt,
		&i.Source,
	)
	return i, err
}

const listStatementsForPortfolio = `-- name: ListStatementsForPortfolio :many
SELECT id, ingest_key, status, submitted_at, updated_at, source
FROM monthly_statements
WHERE user_id = $1 AND portfolio_name = $2 AND reference_date = $3
ORDER BY submitted_at DESC
`

type ListStatementsForPortfolioParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	PortfolioName string      `json:"portfolio_name"`
	ReferenceDate pgtype.Date `json:"reference_date"`
}

type ListStatementsForPortfolioRow struct {
	ID          pgtype.UUID        `json:"id"`
	IngestKey   string             `json:"ingest_key"`
	Status      string             `json:"status"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Source      string             `json:"source"`
}

func (q *Queries) ListStatementsForPortfolio(ctx context.Context, arg ListStatementsForPortfolioParams) ([]ListStatementsForPortfolioRow, error) {
	rows, err := q.db.Query(ctx, listStatementsForPortfolio, arg.UserID, arg.PortfolioName, arg.ReferenceDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementsForPortfolioRow
	for rows.Next() {
		var i ListStatementsForPortfolioRow
		if err := rows.Scan(
			&i.ID,
			&i.IngestKey,
			&i.Status,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
