// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (CreateIdempotencyKeyRow, error)
	CreateMonthlyStatement(ctx context.Context, arg CreateMonthlyStatementParams) (CreateMonthlyStatementRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	ListStatementsForPortfolio(ctx context.Context, arg ListStatementsForPortfolioParams) ([]ListStatementsForPortfolioRow, error)
}

var _ Querier = (*Queries)(nil)
